### ISSUE TITLE
Timestamps not working on Linux

### ISSUE THREAD

**Issue by MichaelTunnell** [partouf/OBSInfoWriter#25]
First of all, thank you so much for taking the time to make this plugin . . . this has so much potential to save me a ton of time so I am so excited to use this. :+1: 

Unfortunately, it is not currently sending timestamps to the txt file whether I am recording, streaming or both.

I am using v1.1 of this plugin and everything else seems to work like creating files based on the date, logging scene switching, track when I start and stop streams/recordings, and it does log that I hit the hotkeys . . . but unfortunately it isn't sending timestamps.

I am using **Ubuntu 16.04** (via KDE Neon) [Linux] and OBS 22.0.2.

-----

I also submitted a pull request for adding Linux installation howto. [pr24](https://github.com/partouf/OBSInfoWriter/pull/24)

**Comment by partouf** [comment]
Can you expand on what you're seeing in the logfile and how your settings are?

**Comment by MichaelTunnell** [comment]
Here is the result that I get in the logfile. I setup 2 hotkeys to indicate stop and start for segments.

```
START RECORDING @ 2018-09-16 09:28:21
 - Segment Recording Start
 - Scene changed to Topic 1
 - Segment Recording Start
 - Segment Recording End
 - Scene changed to LIVE Streaming
STOP RECORDING @ 2018-09-16 09:31:39

START RECORDING @ 2018-09-16 09:32:36
START STREAM @ 2018-09-16 09:32:49
 - Scene changed to Topic 1
 - Segment Recording Start
 - Segment Recording End
 - Scene changed to LIVE Streaming
STOP RECORDING @ 2018-09-16 09:33:56

STOP STREAM @ 2018-09-16 09:33:57
```

![infowriter-settings-source](https://user-images.githubusercontent.com/1056731/45599788-8ec18100-b9b7-11e8-9a43-c11e327295d6.png)

![infowriter-settings-hotkeys](https://user-images.githubusercontent.com/1056731/45599789-91bc7180-b9b7-11e8-81cb-04c3e3a624ae.png)

**Comment by MichaelTunnell** [comment]
I just tried out the updated plugin and it worked great! This is AWESOME!!!
