### ISSUE TITLE
Increase Limit of HotKeys from 5 to 10?

### ISSUE THREAD

**Issue by MichaelTunnell** [partouf/OBSInfoWriter#26]
This isn't a deal breaker, I can work around this limit if I must but it would be great if the number of hotkeys could be increased from 5 to 10. This way I could be more specific to the changes I am doing during the recording.

If you think a higher number would be better, feel free to do that but for my current needs 10 would be enough.

**Comment by partouf** [comment]
Hi, thanks for feedback. I'll see what I can do!

**Comment by RetroGamer74** [comment]
Can't build your project because some dependencies, which is Groundfloor/Molecules/String.h. And also the obs-module.h. Could you add this a submodules in your project, even linking to other github if needed.

Thanks.

**Comment by partouf** [comment]
The instruction on how to build is here https://github.com/partouf/OBSInfoWriter/blob/master/Build.md

Let me know if something doesn’t work like the documentation says.

**Comment by MichaelTunnell** [comment]
@RetroGamer74 this is unrelated to the hotkeys subject. Please, create your own issues rather than posting unrelated comments to existing threads. (this is a suggestion for all GitHub projects)

**Comment by RetroGamer74** [comment]
You're right. My fault. But I was to compile it by myself to add more hotkeys, so my brain did the rest. Sorry.

**Comment by MichaelTunnell** [comment]
oh I see, the additional context makes it related. If you were adding hotkeys to test then that would be related. Now having that context, as you were and if you get it working with the extra hotkeys please let me know. :sunglasses:

**Comment by RetroGamer74** [comment]
Sure. If I could find those 2 missing files, I could do the fix very fast. I did anyway the post in a new issue.
Cheers.

**Comment by RetroGamer74** [comment]
> The instruction on how to build is here https://github.com/partouf/OBSInfoWriter/blob/master/Build.md Let me know if something doesn’t work like the documentation says.
> […](#)
> On 14 Apr 2019, at 08:35, RetroGamer ***@***.***> wrote: Can't build your project because some dependencies, which is Groundfloor/Molecules/String.h. And also the obs-module.h. Could you add this a submodules in your project, even linking to other github if needed. Thanks. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi thanks for the feedback. I built the DLL but once located in OBS I can not find the plugin entry in the Sources list. Don't know what I'm missing. Any suggestion? Thanks.

**Comment by RetroGamer74** [comment]
18:12:34.850: LoadLibrary failed for '../../obs-plugins/64bit/OBSInfoWriter.dll': The specified module could not be found.
18:12:34.850:  (126)
18:12:34.850: Module '../../obs-plugins/64bit/OBSInfoWriter.dll' not loaded

**Comment by RetroGamer74** [comment]
Well found the issue. Got everything working. I will do a fork of your project and will do the release in a few.
Thanks.

**Comment by RetroGamer74** [comment]
> oh I see, the additional context makes it related. If you were adding hotkeys to test then that would be related. Now having that context, as you were and if you get it working with the extra hotkeys please let me know. 😎

Hi bro, don't want to do spam, but in my own Github, I did the fork of this project, I did the modifications, and I built the new OBSInfoWriter.dll for 64 bits only. You can get it here: https://github.com/RetroGamer74/OBSInfoWriter/releases/tag/1.2

Thank you.

**Comment by MichaelTunnell** [comment]
@RetroGamer74 you should submit a pull request to this repo

**Comment by partouf** [comment]
I will probably accept the PR right away

**Comment by MichaelTunnell** [comment]
@RetroGamer74 please send a pull request for your changes. I do not use Windows so the .dll file you created is not usable to me. If you submit a pull request then partouf could rebuild the .so file I need. Please submit :D

**Comment by partouf** [comment]
Changes have been merged.
https://github.com/partouf/OBSInfoWriter/releases/tag/v1.2
