### ISSUE TITLE
Option to Donate?

### ISSUE THREAD

**Issue by MichaelTunnell** [partouf/OBSInfoWriter#28]
I use this plugin basically every day so its quite valuable to me. id like to donate to show my gratitude. Do you have an option for donations?

This is not an attempt to get my issue updated or anything, this just improves my workflow so well as is that I want to show my appreciation.

I used to do timestamps manually until I was introduced to this plugin, this plugin saves me hours of work now on production.

**Comment by partouf** [comment]
I had added a Sponsor button on top of the Github page that links to a special Paypal page for donations, should you be inclined. It is of course in no way necessary.
