### ISSUE TITLE
Feature idea: Export EDL format

### ISSUE THREAD

**Issue by tensiondriven** [partouf/OBSInfoWriter#31]
Any chance of getting an output option that would be EDL-compatible, or compatible with some format that could allow marker information to be imported into Davinci Resolve, Premier etc?

I don't know much about these formats, but I know that my workflow is:
1. Record live stream to disk with OBS
2. Edit down the file in OBS, selecting interesting parts

If I could get the markers to show up in Resolve, that would be amazing.

**Comment by partouf** [comment]
Included in v2.0 - now downloadable from here and the forums
