### ISSUE TITLE
Plugin load fails

### ISSUE THREAD

**Issue by alejandro** [partouf/OBSInfoWriter#32]
Hi! Sorry for this issue but I can't find a solution: I am trying to add some small changes (3LOC) to this plugin but I can't make it load on OBS. OBS keeps throwing this error:

`9:05:44.125: LoadLibrary failed for '../../obs-plugins/64bit/OBSInfoWriter.dll': The specified module could not be found.
09:05:44.125:  (126)
09:05:44.125: Module '../../obs-plugins/64bit/OBSInfoWriter.dll' not loaded`

My build is ok, What am I missing? Thanks for your help-

**Comment by partouf** [comment]
It might be that you build the dll using the wrong visual c++ runtime. I think it needs Visual Studio 2015 (v140)

**Comment by alejandro** [comment]
Actually that's the one I am using, tried 145, 142, 140... No luck.

![obs](https://user-images.githubusercontent.com/542199/76102047-02cd5b80-5f95-11ea-8420-2aa6b80a6d50.png)

**Comment by partouf** [comment]
It seems the most recent version of OBSStudio has 2017 as a runtime, I'm currently working on a new version. I'm not encountering any issues with it.

**Comment by partouf** [comment]
Closing for now, let me know if you have any more problems
