### ISSUE TITLE
CSV Format

### ISSUE THREAD

**Issue by Skrappjaw** [partouf/OBSInfoWriter#33]
Format output options would be amazing. I do Editing in reaper and it has CSV import features.

example reaper format

Name,Start
marker,0:00:00:00
marker,0:00:00:20

This format would make everything amazing.

**Comment by Skrappjaw** [comment]
Here's some linux terminal commands that you can use. Also helps to add an extra :00 at the end of the format in the OBS options. %d:%02d:%02d:00 <--

> 
>$ sed -i 's/.*RECORDING.*//' timestamps.txt
> $ sed -i 's/-//g' timestamps.txt
> $ sed -i '1 c\Start Name' timestamps.txt
> $ cp timestamps.txt timestamps.csv

**Comment by partouf** [comment]
Officially posted the new version that includes this feature.
