### ISSUE TITLE
InfoWriter not loading

### ISSUE THREAD

**Issue by Pyr47** [partouf/OBSInfoWriter#34]
I've tried a couple different Macs running High Sierra and Mojave and different versions of OBS Studio and I experience the same error in the logs of both. InfoWriter fails to load.

06:05:47.215: [Python] Could not load library: libpython3.7m.dylib
06:05:47.216: os_dlopen(/Applications/OBS.app/Contents/Plugins/libOBSInfoWriter.so->/Applications/OBS.app/Contents/Plugins/libOBSInfoWriter.so): dlopen(/Applications/OBS.app/Contents/Plugins/libOBSInfoWriter.so, 257): Library not loaded: @rpath/../bin/libobs.0.dylib
06:05:47.216:   Referenced from: /Applications/OBS.app/Contents/Plugins/libOBSInfoWriter.so
06:05:47.216:   Reason: image not found
06:05:47.216: 
06:05:47.216: Module '/Applications/OBS.app/Contents/Plugins/libOBSInfoWriter.so' not loaded

**Comment by partouf** [comment]
Not sure why there's a python error, I'm guessing that's for a different plugin.

I'm not sure about the problem, perhaps the libobs library has changed name or path, I can only fix that by recompiling on a recent mac os.

Currently working on a new version and will make sure everything will work on Mac as well.

**Comment by partouf** [comment]
Can you see if you can load the latest version? https://github.com/partouf/OBSInfoWriter/releases/download/v2.0-alpha/libOBSInfoWriter.v2.0-alpha.OSX.zip

It's build against OBS 24.0.6

**Comment by Pyr47** [comment]
Yes!

Haven't tried it yet but at least it's loading now.

[image: image.png]

Thank you very much for your efforts.

Jacob Fenn
FennWorld.com <https://www.fennworld.com>

**Comment by Pyr47** [comment]
It appears to be working as expected. Thank you kindly. Do you have a
donation page anywhere?

Jacob Fenn
FennWorld.com <https://www.fennworld.com>

**Comment by partouf** [comment]
It's of course in no way necessary, but because more people have been asking, I have made a special Paypal page for this project at https://paypal.me/pools/c/8oapwHETe5
