### ISSUE TITLE
OBSInfoWriter not accounting for paused time during recordings

### ISSUE THREAD

**Issue by ErvinCSE** [partouf/OBSInfoWriter#35]
Hello! Thank you for making this wonderful plugin, it's already saved me tons of time.

It appears that the log file bases its timestamps on the system's clock, and not based on the OBS recording timer. This means that anyone who uses the "Pause Recording" function in OBS will have misplaced timestamps after resuming their recordings.

Is there a way this paused time could be accounted for?

Edit: it appears PR #30 addresses this issue but it has yet to be pulled in.

**Comment by partouf** [comment]
This will indeed be the case with the PR. I'm currently working on a new version that includes these changes.

**Comment by TheTawnyFool** [comment]
Awesome, my changes are getting merged!  Let me know if I can be of any assistance.

**Comment by partouf** [comment]
Posted on the forums as v2.0
