### ISSUE TITLE
Add toggle for "HOTKEY:<hotkey> @ yyyy-MM-dd hh:mm:ss"

### ISSUE THREAD

**Issue by TriFerd** [partouf/OBSInfoWriter#38]
I used InfoWriter a while back and really liked its straight forward timestamp format. I took a break for some months and when I got back into it I saw that some additional information is being printed to the log file.

I would really appreciate a toggle of some sort to remove the absolute times when pressing a hotkey.

To make this as clear as possible, down below is an example. I would like to be able to toggle off the lines marked with `<<<`.

```
EVENT:START RECORDING @ 2020-05-02 16:37:35
00:00:00 Record Time Marker

HOTKEY:timestamp @ 2020-05-02 16:37:40 <<<
00:00:05 Record Time Marker

HOTKEY:timestamp @ 2020-05-02 16:37:41 <<<
00:00:06 Record Time Marker

HOTKEY:timestamp @ 2020-05-02 16:37:42 <<<
00:00:07 Record Time Marker

HOTKEY:timestamp @ 2020-05-02 16:37:42 <<<
00:00:07 Record Time Marker

HOTKEY:timestamp @ 2020-05-02 16:37:43 <<<
00:00:08 Record Time Marker

EVENT:STOP RECORDING @ 2020-05-02 16:37:45 Record Time Marker Reset to 0
00:00:00 Record Time Marker (not recording)
```

I would also really appreciate an option to remove "Record Time Marker" from the timestamps themselves.

**Comment by partouf** [comment]
Hey, thanks for the feedback! and sorry for the late response. I haven't found time to look into this yet, but I'm hoping to find some next week.

**Comment by partouf** [comment]
I have incorporated your suggestion in v2.1 https://github.com/partouf/OBSInfoWriter/releases/tag/v2.1
Hope it helps

**Comment by TriFerd** [comment]
Yes, that's exactly what I wanted. Thanks for your effort, as well as the quick implementation :)
