### ISSUE TITLE
OBS Crashes Upon Pausing. 

### ISSUE THREAD

**Issue by Nicktheslick69** [partouf/OBSInfoWriter#43]
Hello, I'd like to start off by saying this plugin is exactly what I have been wishing for since I first installed OBS. I'd like to thank you for developing this in your recreational time, I am having some issues regarding pausing and I would like to get to the bottom of it considering I use the feature very frequently. I will attach a log of the crash from OBS and I am using OBS version 25.0.8
[Crash 2020-08-31 17-48-59 (1).txt](https://github.com/partouf/OBSInfoWriter/files/5152800/Crash.2020-08-31.17-48-59.1.txt)

I also want to apologize for the formatting since I am on mobile currently.

**Comment by partouf** [comment]
Thanks for the crashlog! Can you share your settings that you use for the plugin?

**Comment by Nicktheslick69** [comment]
> Thanks for the crashlog! Can you share your settings that you use for the plugin?

Yes I can, I modified the timestamp format according to the website you provided so it may be incorrect but you can be the judge of that. 

I also wanted to let you know I tried a fresh install of OBS and reinstalled the plugin just to see if that was the problem. It did not change anything. 
![image](https://user-images.githubusercontent.com/21070431/92041280-ef355e80-ed45-11ea-91a4-10a6e817364e.png)

**Comment by partouf** [comment]
Ah, so the Format is only for formatting the seconds from the start of the recording/stream.
The format you have entered only works for the Logfile name.

The default that should work for Format is "%d:%02d:%02d"

(You can test it here if you want to https://godbolt.org/z/4sEqef)

**Comment by Nicktheslick69** [comment]
> Ah, so the Format is only for formatting the seconds from the start of the recording/stream.
> The format you have entered only works for the Logfile name.
> 
> The default that should work for Format is "%d:%02d:%02d"
> 
> (You can test it here if you want to https://godbolt.org/z/qxvc3b)

Alright wow that fixed things nicely, I had no idea the format option was meant for the filename. Thank you very much you can close this issue as it isn't much of an issue just a misunderstanding.
