### ISSUE TITLE
InfoWriter is not showing on Mac

### ISSUE THREAD

**Issue by ViktorKuzmanov** [partouf/OBSInfoWriter#45]
I cannot see InfoWriter when I click on the "add scene" button in OBS
 after adding the .so file in plugins folder (Check image)

![Screen Shot 2021-05-05 at 2 25 46 PM](https://user-images.githubusercontent.com/32278714/117140634-e94cbd00-adad-11eb-81a3-782eb348d72c.jpg)

**Comment by partouf** [comment]
Hi, can you share your logging, please

**Comment by machty** [comment]
@ViktorKuzmanov lisOBSInfoWriter.so is supposed to go in the Plugins folder (which is visible in your screenshare), not the Resources/../obs-plugins folder.

It's showing up for me and I use a mac.

**Comment by proactivematter** [comment]
So, unlike OP mine is actually in the correct folder but it's also not showing up as a source. Here's the log, but I couldn't find anything about "InfoWriter" in it either:

`16:50:34.889: [macOS] Permission for audio device access granted.
16:50:34.892: [macOS] Permission for video device access granted.
16:50:34.896: [macOS] Permission for accessibility granted.
16:50:34.899: [macOS] Permission for screen capture granted.
16:50:34.899: Rosetta translation used: true
16:50:34.899: CPU Name: Apple M1 Max
16:50:34.899: CPU Speed: 2400MHz
16:50:34.899: Physical Cores: 10, Logical Cores: 10
16:50:34.899: Physical Memory: 32768MB Total
16:50:34.899: OS Name: macOS
16:50:34.899: OS Version: Version 12.6 (Build 21G115)
16:50:34.899: Kernel Version: 21.6.0
16:50:34.902: hotkeys-cocoa: Using layout 'com.apple.keylayout.USInternational-PC'
16:50:34.902: Current Date/Time: 2022-10-26, 16:50:34
16:50:34.902: Browser Hardware Acceleration: true
16:50:34.902: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
16:50:34.902: Portable mode: false
16:50:35.043: OBS 28.0.3 (mac)
16:50:35.043: ---------------------------------
16:50:35.044: ---------------------------------
16:50:35.044: audio settings reset:
16:50:35.044: 	samples per sec: 48000
16:50:35.044: 	speakers:        2
16:50:35.044: 	max buffering:   960 milliseconds
16:50:35.044: 	buffering type:  dynamically increasing
16:50:35.046: ---------------------------------
16:50:35.046: Initializing OpenGL...
16:50:35.083: Loading up OpenGL on adapter Apple Apple M1 Max
16:50:35.083: OpenGL loaded successfully, version 4.1 Metal - 76.3, shading language 4.10
16:50:35.348: ---------------------------------
16:50:35.348: video settings reset:
16:50:35.348: 	base resolution:   3840x2160
16:50:35.348: 	output resolution: 3840x2160
16:50:35.348: 	downscale filter:  Bicubic
16:50:35.348: 	fps:               60/1
16:50:35.348: 	format:            NV12
16:50:35.348: 	YUV mode:          Rec. 709/Partial
16:50:35.348: NV12 texture support not available
16:50:35.348: P010 texture support not available
16:50:35.348: Audio monitoring device:
16:50:35.348: 	name: Default
16:50:35.348: 	id: default
16:50:35.348: ---------------------------------
16:50:35.358: No AJA devices found, skipping loading AJA UI plugin
16:50:35.358: Failed to initialize module 'aja-output-ui'
16:50:35.364: No AJA devices found, skipping loading AJA plugin
16:50:35.364: Failed to initialize module 'aja'
16:50:35.367: Failed to load 'en-US' text for module: 'decklink-captions'
16:50:35.370: Failed to load 'en-US' text for module: 'decklink-output-ui'
16:50:35.371: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:50:35.372: Failed to initialize module 'decklink'
16:50:36.581: [VideoToolbox encoder]: Adding VideoToolbox encoders
16:50:36.613: [obs-browser]: Version 2.18.5
16:50:36.613: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
16:50:36.634: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
16:50:36.634: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
16:50:36.634: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
16:50:36.638: [obs-websocket] [obs_module_load] Module loaded.
16:50:36.644: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 0x0101): tried: '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
16:50:36.644: 
16:50:36.644: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
16:50:36.655: <StreamDeck> Plugin version 5.3.2.27
16:50:36.655: <StreamDeck> [Server] Listening on '127.0.0.1:28186'.
16:50:36.655: os_dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginQt6->/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginQt6.so): dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginQt6.so, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginQt6.so' (no such file)
16:50:36.655: 
16:50:36.656: Failed to initialize module 'StreamDeckPlugin.so'
16:50:36.667: ---------------------------------
16:50:36.667:   Loaded Modules:
16:50:36.667:     logi_obs_plugin.so
16:50:36.667:     StreamDeckPlugin
16:50:36.667:     vlc-video
16:50:36.667:     text-freetype2
16:50:36.667:     rtmp-services
16:50:36.667:     obs-x264
16:50:36.667:     obs-websocket
16:50:36.667:     obs-vst
16:50:36.667:     obs-transitions
16:50:36.667:     obs-outputs
16:50:36.667:     obs-filters
16:50:36.667:     obs-ffmpeg
16:50:36.667:     obs-browser
16:50:36.667:     mac-virtualcam
16:50:36.667:     mac-videotoolbox
16:50:36.667:     mac-syphon
16:50:36.667:     mac-capture
16:50:36.667:     mac-avcapture
16:50:36.667:     image-source
16:50:36.667:     frontend-tools
16:50:36.667:     decklink-output-ui
16:50:36.667:     decklink-captions
16:50:36.667:     coreaudio-encoder
16:50:36.667: ---------------------------------
16:50:36.682: ==== Startup complete ===============================================
16:50:36.734: All scene data cleared
16:50:36.734: ------------------------------------------------
16:50:36.835: coreaudio: device 'MacBook Pro Microphone' initialized
16:50:36.856: CAM - MBP: Selected device 'FaceTime HD Camera'
16:50:36.857: CAM - MBP: Using preset 1280x720
16:50:36.862: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: MIC - MBP)
16:50:36.862: 
16:50:36.933: coreaudio: failed to find device uid: AppleUSBAudioEngine:Elgato Systems:Elgato Wave:3:BS17J1A00934:2,1, waiting for connection
16:50:36.933: User selected new VST plugin: '/Library/Audio/Plug-Ins/VST/Marvel GEQ.vst'
16:50:36.958: User selected new VST plugin: '/Library/Audio/Plug-Ins/VST/Plugin Alliance/bx_cleansweep V2.vst'
16:50:37.276: coreaudio: device 'BlackHole 2ch' initialized
16:50:37.278: [Media Source 'MIC Tuner']: settings:
16:50:37.278: 	input:                   /Users/diego/Files_MAC/Creation/OBS/Resources/Room Tone.m4a
16:50:37.278: 	input_format:            (null)
16:50:37.278: 	speed:                   100
16:50:37.278: 	is_looping:              yes
16:50:37.278: 	is_linear_alpha:         no
16:50:37.278: 	is_hw_decoding:          yes
16:50:37.278: 	is_clear_on_media_end:   yes
16:50:37.278: 	restart_on_activate:     yes
16:50:37.278: 	close_when_inactive:     no
16:50:37.278: 	ffmpeg_options:          
16:50:37.278: Set FFmpeg options: 
16:50:37.362: User selected new VST plugin: '/Library/Audio/Plug-Ins/VST/Marvel GEQ.vst'
16:50:37.364: User selected new VST plugin: '/Library/Audio/Plug-Ins/VST/Plugin Alliance/bx_cleansweep V2.vst'
16:50:37.551: Switched to scene 'External - Recording'
16:50:37.553: ------------------------------------------------
16:50:37.553: Loaded scenes:
16:50:37.553: - scene 'External - Recording':
16:50:37.553:     - source: 'MIC Tuner' (ffmpeg_source)
16:50:37.553:         - monitoring: monitor and output
16:50:37.553:         - filter: 'Voxengo' (vst_filter)
16:50:37.553:         - filter: 'Compressor' (compressor_filter)
16:50:37.553:         - filter: 'Noise Gate' (noise_gate_filter)
16:50:37.553:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:50:37.553:         - filter: 'Cleansweep' (vst_filter)
16:50:37.553:     - source: 'Video' (group)
16:50:37.553:     - source: 'Audio' (group)
16:50:37.553: - scene 'External - Streaming':
16:50:37.553:     - source: 'Video' (group)
16:50:37.553:     - source: 'Audio' (group)
16:50:37.553:     - source: 'CAM - MBP' (av_capture_input)
16:50:37.554: - scene 'REG_A_4KTV':
16:50:37.554:     - source: 'MIC Tuner' (ffmpeg_source)
16:50:37.554:         - monitoring: monitor and output
16:50:37.554:         - filter: 'Voxengo' (vst_filter)
16:50:37.554:         - filter: 'Compressor' (compressor_filter)
16:50:37.554:         - filter: 'Noise Gate' (noise_gate_filter)
16:50:37.554:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:50:37.554:         - filter: 'Cleansweep' (vst_filter)
16:50:37.554:     - source: 'CAM - MBP' (av_capture_input)
16:50:37.554:     - source: 'DIS - X900F' (display_capture)
16:50:37.554:     - source: 'MIC - MBP' (coreaudio_input_capture)
16:50:37.554:     - source: 'MIC - Wave:3' (coreaudio_input_capture)
16:50:37.554:         - filter: 'Voxengo' (vst_filter)
16:50:37.554:         - filter: 'Compressor' (compressor_filter)
16:50:37.554:         - filter: 'Noise Gate' (noise_gate_filter)
16:50:37.554:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:50:37.554:         - filter: 'Cleansweep' (vst_filter)
16:50:37.554:     - source: 'System (Blackhole)' (coreaudio_output_capture)
16:50:37.554: - scene 'REG_A_MBPI':
16:50:37.554: - scene 'REG_C_CAM0':
16:50:37.554:     - source: 'MIC Tuner' (ffmpeg_source)
16:50:37.554:         - monitoring: monitor and output
16:50:37.554:         - filter: 'Voxengo' (vst_filter)
16:50:37.554:         - filter: 'Compressor' (compressor_filter)
16:50:37.554:         - filter: 'Noise Gate' (noise_gate_filter)
16:50:37.554:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:50:37.554:         - filter: 'Cleansweep' (vst_filter)
16:50:37.554:     - source: 'CAM - MBP' (av_capture_input)
16:50:37.554:     - source: 'DIS - X900F' (display_capture)
16:50:37.554:     - source: 'MIC - MBP' (coreaudio_input_capture)
16:50:37.554:     - source: 'MIC - Wave:3' (coreaudio_input_capture)
16:50:37.554:         - filter: 'Voxengo' (vst_filter)
16:50:37.554:         - filter: 'Compressor' (compressor_filter)
16:50:37.554:         - filter: 'Noise Gate' (noise_gate_filter)
16:50:37.554:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
16:50:37.554:         - filter: 'Cleansweep' (vst_filter)
16:50:37.554:     - source: 'System (Blackhole)' (coreaudio_output_capture)
16:50:37.554: - scene 'REG_C_CAM1':
16:50:37.554: ------------------------------------------------
`

**Comment by partouf** [comment]
I have built some installers using OBS's plugin template scripts.
I haven't tested it myself, but if you can try them out, please do. https://github.com/partouf/OBSInfoWriter/releases/tag/v2.3

**Comment by proactivematter** [comment]
This worked! Thank you.
