### ISSUE TITLE
OBS 27.1.3 doesn't show hotkeys

### ISSUE THREAD

**Issue by DachsbauTV** [partouf/OBSInfoWriter#48]
Hi @partouf 

Thanks for the great plugin.
I've just installed it for the first time, but unfortunately in the hotkey settings, it only shows Show/Hide infowriter source, but not the hotkeys as options.

Using OBS 27.1.3. on Win10 x64

**Comment by partouf** [comment]
Hmm, strange, I just installed 27.1.3 and they're there for me. Are you sure they're missing? Maybe they're buried between some other plugins?

![image](https://user-images.githubusercontent.com/442630/142873450-7fd9e492-bd5e-4d00-9b37-24a8aae39bd0.png)

**Comment by DachsbauTV** [comment]
Ok nevermind, they are there but they don't show up in the search �
![Screenshot 2021-11-22 at 14 56 20](https://user-images.githubusercontent.com/70434961/142874081-28953b48-b6d2-41a9-b22d-6d19508a9f01.jpg)
�
But that's a 100% my bad for not looking properly... Sorry

**Comment by partouf** [comment]
> Ok nevermind, they are there but they don't show up in the search � ![Screenshot 2021-11-22 at 14 56 20](https://user-images.githubusercontent.com/70434961/142874081-28953b48-b6d2-41a9-b22d-6d19508a9f01.jpg) � But that's a 100% my bad for not looking properly... Sorry

No problem! good to know they're not searchable

**Comment by DachsbauTV** [comment]
I think the solution  for this would be quite easy: Just rename the hotkeys to "infowriter Hotkey 1" "infowriter Hotkey 2" etc
