### ISSUE TITLE
The required OBS28/QT6/Apple Silicon question

### ISSUE THREAD

**Issue by pkej** [partouf/OBSInfoWriter#51]
Hi,
I wonder if you'll be upgrading the plug-in to QT6 and Apple Silicon ?

I see quite a few other developers are using Github actions and workflows to automate builds for all the different platforms. I don't have experience with actions and workflows, so I can't help with it.

**Comment by partouf** [comment]
I'm assuming I won't have to do anything specific for QT6 and Apple, but I do need to update this plugin for the new OBS api's. Thanks for reminding me

**Comment by MichaelTunnell** [comment]
Yes PLEASE!!! :D I love this plugin, it is critical to my workflow (Linux) so I would love it to be updated to v28.

**Comment by partouf** [comment]
I have built some installers using OBS's plugin template scripts.
I haven't tested it myself, but if you can try them out, please do. https://github.com/partouf/OBSInfoWriter/releases/tag/v2.3

**Comment by partouf** [comment]
I just tested it on my mac and the plugin did not show up after running the installer.

I needed to take an extra step (my OSX is probably too old):
* Copy `/Library/Application Support/obs-studio/plugins/OBSInfoWriter.plugin` to the package contents of the OBS application in the plugins folder
