### ISSUE TITLE
Missing archive containing a DLL to copy to plugins directory

### ISSUE THREAD

**Issue by wlawski** [partouf/OBSInfoWriter#64]
OBSInfoWriter v2.3 was the last release for which an archive containing a DLL to copy to plugins directory was created.
Newer releases contain installer for Windows but Microsoft Defender removes it.
Embedded antivirus complains about Trojan (script).
There is also a link to an official Microsoft page: https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Phonzy.C!ml&threatid=2147772968

**Comment by partouf** [comment]
Ah, I'll see if I can get the .zip back. I had to update the CMake scripts of the build process to update everything to work with OBS 29. I'm getting the files from https://github.com/obsproject/obs-plugintemplate but they changed a lot more unfortunately.

I don't really understand why Defender keeps thinking there's a virus.

**Comment by partouf** [comment]
I've made sure only a .zip is generated and tagged it here https://github.com/partouf/OBSInfoWriter/releases/tag/2.6.1
No more setup
