### ISSUE TITLE
What happened to the windows non-installer file for 2.6.0?

### ISSUE THREAD

**Issue by mpek** [partouf/OBSInfoWriter#66]
Don't use the installer much, so wondering if it's just overseen to upload the non-installer version for 2.6.0?

**Comment by SplitCoreGaming** [comment]
If it helps (as I also use portable folders) you can just direct the installer to the portable folder and update/install fine.

**Comment by partouf** [comment]
I've made sure only a .zip is generated and tagged it here https://github.com/partouf/OBSInfoWriter/releases/tag/2.6.1
